// GST State Code to State Name Mapping
export const gstMaps = [
  { gstCode: "01", state: "Jammu and Kashmir" },
  { gstCode: "02", state: "Himachal Pradesh" },
  { gstCode: "03", state: "Punjab" },
  { gstCode: "04", state: "Chandigarh" },
  { gstCode: "05", state: "Uttarakhand" },
  { gstCode: "06", state: "Haryana" },
  { gstCode: "07", state: "Delhi" },
  { gstCode: "08", state: "Rajasthan" },
  { gstCode: "09", state: "Uttar Pradesh" },
  { gstCode: "10", state: "Bihar" },
  { gstCode: "11", state: "Sikkim" },
  { gstCode: "12", state: "Arunachal Pradesh" },
  { gstCode: "13", state: "Nagaland" },
  { gstCode: "14", state: "Manipur" },
  { gstCode: "15", state: "Mizoram" },
  { gstCode: "16", state: "Tripura" },
  { gstCode: "17", state: "Meghalaya" },
  { gstCode: "18", state: "Assam" },
  { gstCode: "19", state: "West Bengal" },
  { gstCode: "20", state: "Jharkhand" },
  { gstCode: "21", state: "Odisha" },
  { gstCode: "22", state: "Chhattisgarh" },
  { gstCode: "23", state: "Madhya Pradesh" },
  { gstCode: "24", state: "Gujarat" },
  { gstCode: "25", state: "Daman and Diu" },
  { gstCode: "26", state: "Dadra and Nagar Haveli" },
  { gstCode: "27", state: "Maharashtra" },
  { gstCode: "28", state: "Andhra Pradesh" },
  { gstCode: "29", state: "Karnataka" },
  { gstCode: "30", state: "Goa" },
  { gstCode: "31", state: "Lakshadweep" },
  { gstCode: "32", state: "Kerala" },
  { gstCode: "33", state: "Tamil Nadu" },
  { gstCode: "34", state: "Puducherry" },
  { gstCode: "35", state: "Andaman and Nicobar Islands" },
  { gstCode: "36", state: "Telangana" },
  { gstCode: "37", state: "Andhra Pradesh" },
];
